name: Run Gradle
description: Sets up Gradle JDKs and runs Gradle
inputs:
  arguments:
    required: false
    description: Gradle arguments
  java:
    required: true
    description: The JDK version
  distribution:
    default: temurin
    required: false
    description: The Java distribution
  cache-encryption-key:
    required: false
    description: A Gradle cache encryption key
  attempt-limit:
    default: '1'
    required: false
    description: Number of attempts
  attempt-delay:
    default: '0'
    required: false
    description: A delay between attempts in seconds
runs:
  using: composite
  steps:
    - name: Setup shell
      if: runner.os == 'macOS'
      shell: bash
      run: |
        brew install bash
        echo "/opt/homebrew/bin/bash" >> $GITHUB_PATH || \
        echo "/usr/local/bin/bash" >> $GITHUB_PATH
        brew install grep
        echo "/opt/homebrew/opt/grep/libexec/gnubin" >> $GITHUB_PATH || \
        echo "/usr/local/opt/grep/libexec/gnubin" >> $GITHUB_PATH
    - name: Read Gradle JDK toolchain version
      id: gradle_toolchain
      shell: bash
      run: |
        toolchainVersion=$(grep -oP '(?<=^toolchainVersion=).*' gradle/gradle-daemon-jvm.properties)
        echo "version=${toolchainVersion}" >> $GITHUB_OUTPUT
    - name: Set up JDK ${{ steps.gradle_toolchain.outputs.version }}
      uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4.7.1
      with:
        java-version: ${{ steps.gradle_toolchain.outputs.version }}
        distribution: temurin
    - name: Set up JDK
      uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4.7.1
      with:
        java-version: ${{ inputs.java }}
        distribution: ${{ inputs.distribution }}
    - name: Prepare JDK toolchain
      id: java_toolchain
      env:
        INPUTS_JAVA: ${{ inputs.java }}
        JDK_EA: ${{ endsWith(inputs.java, '-ea') }}
        INPUTS_DISTRIBUTION: ${{ inputs.distribution }}
      shell: bash
      run: |
        declare -A -r VENDORS=(
          ["temurin"]="Adoptium"
          ["graalvm"]="GraalVM Community"
        )
        version="${INPUTS_JAVA%-ea}"
        vendor=${VENDORS["$INPUTS_DISTRIBUTION"]}

        if [[ "$INPUTS_DISTRIBUTION" == "graalvm" ]]; then
          echo "graalvm_home=$JAVA_HOME" >> $GITHUB_OUTPUT
        fi
        echo "distribution=$INPUTS_DISTRIBUTION" >> $GITHUB_OUTPUT
        echo "early_access=$JDK_EA" >> $GITHUB_OUTPUT
        echo "java_home=$JAVA_HOME" >> $GITHUB_OUTPUT
        echo "version=$version" >> $GITHUB_OUTPUT
        echo "vendor=$vendor" >> $GITHUB_OUTPUT
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@ac638b010cf58a27ee6c972d7336334ccaf61c96 # v4.4.1
      with:
        cache-read-only: false
        add-job-summary: on-failure
        cache-overwrite-existing: true
        gradle-home-cache-strict-match: true
        gradle-home-cache-includes: |
          caches
          notifications
          wrapper/dists
        cache-encryption-key: ${{ inputs.cache-encryption-key }}
    - name: Run ${{ inputs.arguments }}
      if: ${{ inputs.arguments != '' }}
      env:
        INPUTS_ARGUMENTS: ${{ inputs.arguments }}
        INPUTS_ATTEMPT_DELAY: ${{ inputs.attempt-delay }}
        INPUTS_ATTEMPT_LIMIT: ${{ inputs.attempt-limit }}
        JDK_CI: ${{ steps.java_toolchain.outputs.java_home }}
        JDK_EA: ${{ steps.java_toolchain.outputs.early_access }}
        JAVA_VENDOR: ${{ steps.java_toolchain.outputs.vendor }}
        JAVA_VERSION: ${{ steps.java_toolchain.outputs.version }}
        JDK_DISTRIBUTION: ${{ steps.java_toolchain.outputs.distribution }}
        GRAALVM_HOME: ${{ steps.java_toolchain.outputs.graalvm_home }}
        ORG_GRADLE_PROJECT_org.gradle.java.installations.auto-download: false
      shell: bash
      run: |
        echo "::add-matcher::.github/problem-matcher.json"
        for ((i=1; i<=$INPUTS_ATTEMPT_LIMIT; i++)); do
          ./gradlew --no-problems-report $(eval echo "$INPUTS_ARGUMENTS" | tr -d '\n') && break
          if [ $i -lt $INPUTS_ATTEMPT_LIMIT ]; then
            echo "Attempt $i failed. Retrying in $INPUTS_ATTEMPT_DELAY seconds..."
            sleep $INPUTS_ATTEMPT_DELAY
          else
            echo "All attempts failed."
            exit 1
          fi
        done
